# Assignment Numpy

1. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def gen_Vandermond_matrix(input_vector: 'ndarray', no_col: int, increasing: bool) -> 'ndarray':
    '''
    Columns of the output matrix are powers of the input vector.
    
    Parameters:
    -------------------
    input_vector: input vector in the form of ndarray
    no_col: Number of columns in output matrix
    increasing: bool type parameter to control the order of order of powers
    
    Returns:
    -------------------
    Returns an ndarray with columns  are powers of the input vector
    '''
    if(increasing == True):
        output_matrix = np.array([x**i for x in input_vector for i in range(no_col)]).reshape(input_vector.size,no_col)
    else:
        output_matrix = np.array([x**(no_col-i-1) for x in input_vector for i in range(no_col)]).reshape(input_vector.size,no_col)
    
    return output_matrix

### Output:

In [3]:
input_vector=np.array([2,3,5,6,7])
no_col= 5
output_matrix_inc_order = gen_Vandermond_matrix(input_vector, no_col, increasing=True)
output_matrix_dec_order = gen_Vandermond_matrix(input_vector, no_col, increasing=False)
print('Input Vector Is: \n',input_vector)
print('\nNumber Of Columns in output matrix: ',no_col)
print('\nVandermond matrix in  increasing order of power: \n\n',output_matrix_inc_order)
print('\nVandermond matrix in  decreasing order of power: \n\n',output_matrix_dec_order)

Input Vector Is: 
 [2 3 5 6 7]

Number Of Columns in output matrix:  5

Vandermond matrix in  increasing order of power: 

 [[   1    2    4    8   16]
 [   1    3    9   27   81]
 [   1    5   25  125  625]
 [   1    6   36  216 1296]
 [   1    7   49  343 2401]]

Vandermond matrix in  decreasing order of power: 

 [[  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]
 [2401  343   49    7    1]]


2. Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below:

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

#### Method1

In [4]:
def moving_average(input_vector: 'ndarray', k: int)->'ndarray':
    '''
    Find Moving Average of an array over a window size
    
    Parameter:
    ---------------------------
    input_vector: input vector in the form of ndarray
    k: Window_Size for which the average will be calculated
    
    Return
    ---------------------------
    Returns an ndarray for the moving average over a window size
    
    '''
    cumulative_sum = np.cumsum(input_vector)
    cumulative_sum[k:] = cumulative_sum[k:] - cumulative_sum[:-k]
    moving_avg = cumulative_sum[k-1:]/k
    return moving_avg

### Output

In [5]:
input_vector = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size=3
moving_average_array = moving_average(input_vector,window_size )
print('Input Vector Is: \n',input_vector)
print('\nWindow_Size for which the average will be calculated: ',window_size)
print('\nArray of size {0} with moving average calculation is \n\n {1} '.format((input_vector.size-window_size+1),moving_average_array))

Input Vector Is: 
 [  3   5   7   2   8  10  11  65  72  81  99 100 150]

Window_Size for which the average will be calculated:  3

Array of size 11 with moving average calculation is 

 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333] 


#### Method2

In [6]:
def moving_average(input_vector: 'ndarray', k: int)->'ndarray':
    '''
    Find Moving Average of an array over a window size
    
    Parameter:
    ---------------------------
    input_vector: input vector in the form of ndarray
    k: Window_Size for which the average will be calculated
    
    Return
    ---------------------------
    Returns an ndarray for the moving average over a window size
    
    '''
    moving_avg = np.array([sum(input_vector[i:i+3])/window_size for i in range(input_vector.size-window_size+1)])
    return moving_avg

### Output:

In [7]:
input_vector = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size=3
moving_average_array = moving_average(input_vector,window_size )
print('Input Vector Is: \n',input_vector)
print('\nWindow_Size for which the average will be calculated: ',window_size)
print('\nArray of size {0} with moving average calculation is \n\n {1} '.format((input_vector.size-window_size+1),moving_average_array))

Input Vector Is: 
 [  3   5   7   2   8  10  11  65  72  81  99 100 150]

Window_Size for which the average will be calculated:  3

Array of size 11 with moving average calculation is 

 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333] 
